language: ruby
rvm:
  - 2.7.0

before_install:
  - gem install bundler

before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rspec
