language: ruby
rvm:
  - 2.7.0

script:
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create 
  - bundle exec rake db:migrate
  - bundle exec rspec

before_install:
  - gem install bundler
